# _quarto.yml - Simple Quarto Configuration for Hermes RAG

project:
  title: "AG"
  type: website


website:
  title: "AG"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: second.qmd
        text: Personal Note

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
    code-link: true
